version: '3.2'

# used for staging purpose only. DO NOT use this to deploy the application to production
services:

  fpm:
    build: docker/dev/fpm
    #image: alexdebril/feed-io-api-fpm:v0.1.3
    environment:
      APP_ENV: dev
      APP_SECRET: change_me
      ALLOWED_ORIGIN: localhost
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/newfeeds"
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "feedio_api"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WS_URL: http://ws:8080/item
    links:
      - redis
      - mongo
    volumes:
    - .:/var/www/html

  ws:
    image: alexdebril/feed-io-api-ws:latest
    ports:
      - 8000:8080

  nginx:
    depends_on:
      - fpm
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './public:/var/www/html/public:cached'
      - './docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

  consumer:
    build: docker/dev/cli
    restart: always
    command: "./bin/console messenger:consume async-new-feed -vv"
    environment:
      APP_ENV: dev
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/newfeeds"
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "feedio_api"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WS_URL: http://ws:8080/item
    links:
      - redis
      - mongo
    volumes:
      - .:/srv/feed-io-api/app

  updater:
    build: docker/dev/cli
    restart: always
    command: "./bin/console app:update -vv"
    environment:
      APP_ENV: dev
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "feedio_api"
      WS_URL: http://ws:8080/item
    links:
      - mongo
    volumes:
      - .:/srv/feed-io-api/app

  cli:
    build: docker/dev/cli
    environment:
      APP_ENV: dev
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "feedio_api"
    links:
      - mongo
    volumes:
      - .:/srv/feed-io-api/app

  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_DATABASE: feedio_api
    volumes:
      - ./Resources/database/init.js:/docker-entrypoint-initdb.d/init.js
      - './data/db:/data/db'

  redis:
    image: redis
    hostname: redis
