version: '3.2'

# used for staging purpose only. DO NOT use this to deploy the application to production
services:

  fpm:
    build: docker/dev/fpm
    environment:
      APP_ENV: dev
      APP_SECRET: change_me
      ALLOWED_ORIGIN: localhost
    volumes:
    - .:/var/www/html

  nginx:
    depends_on:
      - fpm
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './public:/var/www/html/public:cached'
      - './docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
