feed_consume:
    path: /feed/consume
    methods: ["POST"]
    controller: App\Controller\FeedController::consume

feed_discover:
    path: /feed/discover
    methods: ["POST"]
    controller: App\Controller\FeedController::discover

